package context

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"bay/internal/config"
	"bay/internal/session"

	"gopkg.in/yaml.v3"
)

// ResourceTypes lists the supported resource directory types.
var ResourceTypes = []string{"rules", "skills", "agents", "plugins"}

// resourceTypeDescriptions maps type to a human-readable description.
var resourceTypeDescriptions = map[string]string{
	"rules":   "Rules, coding standards, documentation",
	"skills":  "Reusable skill definitions",
	"agents":  "Agent configurations",
	"plugins": "Plugin definitions",
}

// indexEntry represents a single resource in index.yaml.
type indexEntry struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
	Scope       string `yaml:"scope"`
	Category    string `yaml:"category"`
	Path        string `yaml:"path"`
}

// indexFile represents the index.yaml structure.
type indexFile struct {
	Type      string       `yaml:"type"`
	Resources []indexEntry `yaml:"resources"`
}

// EnsureResourceDirs creates rules/, skills/, agents/, plugins/, and context/projects/ under ~/.bay/ if missing.
func EnsureResourceDirs() {
	bayDir := config.BayDir()
	for _, t := range ResourceTypes {
		os.MkdirAll(filepath.Join(bayDir, t), 0755)
	}
	os.MkdirAll(config.ContextProjectsDir(), 0755)
}

// GenerateNavigator writes ~/.bay/CLAUDE.md — the agent entry point.
func GenerateNavigator() error {
	bayDir := config.BayDir()
	navigatorPath := filepath.Join(bayDir, "CLAUDE.md")

	var b strings.Builder
	b.WriteString("# Bay Resources\n\n")
	b.WriteString("Bay manages resources in `~/.bay/`. Each directory has an `index.yaml`\n")
	b.WriteString("listing available items. Only read a resource when its description\n")
	b.WriteString("matches your current task.\n\n")
	b.WriteString("## Resource Directories\n\n")
	b.WriteString("| Directory | Type | Description |\n")
	b.WriteString("|-----------|------|-------------|\n")

	for _, t := range ResourceTypes {
		desc := resourceTypeDescriptions[t]
		b.WriteString(fmt.Sprintf("| `~/.bay/%s/` | %s | %s |\n", t, t, desc))
	}

	b.WriteString("\nRead the `index.yaml` in a directory to see available resources.\n")
	b.WriteString("Manage with: `bay context ls|add|rm|toggle`\n")

	b.WriteString("\n## Project Context\n\n")
	b.WriteString("Project-specific context lives in `~/.bay/context/projects/<project-name>/`.\n")
	b.WriteString("Use this directory to store persistent project knowledge that agents need\n")
	b.WriteString("across sessions — architecture docs, status, design decisions, conventions.\n\n")
	b.WriteString("Structure: `~/.bay/context/projects/<project>/` with markdown files.\n")
	b.WriteString("Example: `~/.bay/context/projects/myapp/architecture.md`\n")

	return os.WriteFile(navigatorPath, []byte(b.String()), 0644)
}

// GenerateAllIndexes generates index.yaml for each resource type directory.
func GenerateAllIndexes() error {
	files, err := List()
	if err != nil {
		return fmt.Errorf("listing context files: %w", err)
	}

	// Group by type
	grouped := make(map[string][]ContextFile)
	for _, f := range files {
		if !f.Enabled {
			continue
		}
		t := f.Type
		if t == "" {
			t = "rules"
		}
		grouped[t] = append(grouped[t], f)
	}

	bayDir := config.BayDir()
	for _, t := range ResourceTypes {
		idx := indexFile{
			Type:      t,
			Resources: []indexEntry{},
		}

		for _, f := range grouped[t] {
			idx.Resources = append(idx.Resources, indexEntry{
				Name:        f.Name,
				Description: f.Description,
				Scope:       f.Scope,
				Category:    f.Category,
				Path:        f.Path,
			})
		}

		data, err := yaml.Marshal(&idx)
		if err != nil {
			return fmt.Errorf("marshaling index for %s: %w", t, err)
		}

		header := "# Auto-generated by bay. Do not edit.\n"
		indexPath := filepath.Join(bayDir, t, "index.yaml")
		if err := os.WriteFile(indexPath, []byte(header+string(data)), 0644); err != nil {
			return fmt.Errorf("writing %s/index.yaml: %w", t, err)
		}
	}

	return nil
}

// CleanupWorktreeRules removes .claude/rules/bay/ from all worktree sessions.
func CleanupWorktreeRules() (int, error) {
	sessions, err := session.List()
	if err != nil {
		return 0, fmt.Errorf("listing sessions: %w", err)
	}

	cleaned := 0
	for _, s := range sessions {
		if !s.IsWorktree {
			continue
		}
		bayRulesDir := filepath.Join(s.WorkingDir, ".claude", "rules", "bay")
		if _, err := os.Stat(bayRulesDir); err == nil {
			if err := os.RemoveAll(bayRulesDir); err == nil {
				cleaned++
			}
		}
	}
	return cleaned, nil
}

// EnsureClaudeMDPointer adds a pointer line to ~/.claude/CLAUDE.md if not already present.
func EnsureClaudeMDPointer() {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}

	claudeMDPath := filepath.Join(home, ".claude", "CLAUDE.md")
	pointerLine := "For Bay-managed resources (rules, docs, skills, agents), read ~/.bay/CLAUDE.md"

	// Read existing content
	data, err := os.ReadFile(claudeMDPath)
	if err == nil && strings.Contains(string(data), pointerLine) {
		return // Already present
	}

	// Ensure directory exists
	os.MkdirAll(filepath.Dir(claudeMDPath), 0755)

	// Append pointer line
	f, err := os.OpenFile(claudeMDPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return
	}
	defer f.Close()

	prefix := "\n"
	if len(data) == 0 {
		prefix = ""
	}
	f.WriteString(prefix + pointerLine + "\n")
}
